server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/watchlistdb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: WATCH-LIST
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
    
    
