server:
  port: 9090
spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      mvc:
        routes:
          - id: ANIME-CATALOG
            uri: lb://ANIME-CATALOG
            predicates:
              - Path=/anime/**
          - id: WATCH-LIST
            uri: lb://WATCH-LIST
            predicates: 
              - Path=/watch-list/**
          - id: OLLAMA-AI
            uri: lb://OLLAMA-AI
            predicates:
                - Path=/ollamaaiApi/**
          - id: OPENAI-SERVICE
            uri: lb://OPENAI-SERVICE
            predicates:
                - Path=/openaiApi/**
          - id: ANIME-FINDER
            uri: lb://ANIME-FINDER
            predicates:
                - Path=//api/anime-finder-bot/**
